---
# tasks file for nginx-webserver
- name: Update repositories cache and install "nginx" package
  yum:
    name: nginx
    state: latest
    
- name: start nginx
  service:
    name: nginx
    state: started